---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: wordcount-hpa
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: flink.k8s.io/v1beta1
    kind: FlinkApplication
    name: wordcount-operator-example
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 1
  behavior:
    scaleDown:
      policies:
        - type: Percent
          value: 200
          periodSeconds: 1
    scaleUp:
      policies:
        - type: Percent
          value: 200
          periodSeconds: 1
